### ISSUE TITLE
Создать страницу регистрации и входа

### ISSUE THREAD

**Issue by maxbl4** [maxbl4/RaceLog3#2]
В гуе сделать страницы для регистрации и входа:

- Найти в меше настройки проверки регистрации. И для тестов выключить все проверки, чтобы можно было регистрироваться под любым емейлом и сразу получать доступ
- Сделать гуй для регистрации и входа
- Фронтенд должен поддерживать активную сессию (хранить куку или GWT или что там используется).
**Ожидаемый результат:** возможность зарегистрироваться без проверки емейла и зайти под этим адресом. Закрыть браузер, опять открыть и убедиться, что мы всё ещё залогинены. Кратко описать в комментарии к задаче где лежат настройки и какие есть варианты

**Comment by komadmi** [comment]
Пара интересных ссылочек:
- https://medium.com/@jcbaey/authentication-in-spa-reactjs-and-vuejs-the-right-way-e4a9ac5cd9a3
- http://blog.logrocket.com/securing-a-react-app/

Попробую запилить что то похожее

**Comment by komadmi** [comment]
Короче, все очень просто. Скачал Mesh и curl, создал там нового юзера и выполнил команды вот отсюда - https://getmesh.io/docs/authentication/#_authentication:

rossi: cm9zc3ZhbDpyb3NzdmFsNDY=
admin: YWRtaW46YWRtaW4=

E:\Soft\curl\curl-7.66.0-win64-mingw\bin>curl -v  GET http://localhost:8080/api/v2/auth/login  -H "authorization: Basic cm9zc3ZhbDpyb3NzdmFsNDY="

mesh.token="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyVXVpZCI6IjhmMTM1NjYyOGRmZjRiMjI5MzU2NjI4ZGZmZGIyMmRhIiwiaWF0IjoxNTcxMzMzODY1LCJleHAiOjE1NzEzMzc0NjV9.7jhDXTQVyVPVCInc4kktHyRhJmpADbbMLC9FOBxOA4s" for domain localhost, path /, expire 1571337465

curl GET http://localhost:8080/api/v2/auth/me -H "Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VyVXVpZCI6IjhmMTM1NjYyOGRmZjRiMjI5MzU2NjI4ZGZmZGIyMmRhIiwiaWF0IjoxNTcxMzMzODY1LCJleHAiOjE1NzEzMzc0NjV9.7jhDXTQVyVPVCInc4kktHyRhJmpADbbMLC9FOBxOA4s"

все работает. Попробую взять примеры вот отсюда - https://github.com/gentics/mesh-react-example и запилить код у нас.

**Comment by maxbl4** [comment]
Круто, я слежу за тобой :)

**Comment by komadmi** [comment]
Вов, щас работаю над веткой "mesh-authentication". Я добился того, что могу подрубиться к mesh из гуя (через промежуточный сервачок, для обхода cors в браузере), авторизоваться по логину и паролю через JWT и получить всю инфу о юзере. Но проблема в том, что нет пока четкой схемы объектов. Давай определимся уже, хотя бы для юзера, что бы знать уже и писать код осознанно. Скажи, какие точно поля должны быть у наших пользователей, а я на них заложусь в коде.

**Comment by maxbl4** [comment]
Я завтра постараюсь вынуть. Но ты и сам можешь глянуть в репозитории Racelog2 , который на битбакет, там есть модели RiderProfile - это сам юзер, есть ещё RiderRegistration - запись юзера в класс на гонке. Есть DatabaseInitializer, он умеет залить в базу примеры данных и там же в коде есть видно как создаются связи. RaceRepository содержит код для записи/чтения этого добра из базы

**Comment by komadmi** [comment]
Глянул. Запилю тогда. Но видимо надо и подо все остальное уже постепенно закладываться. Я вижу там у тебя Команды есть

**Comment by komadmi** [comment]
На данный момент работает вход по мейлу и паролю. UI умеет хранить куку с токеном, так что при перезагрузке страницы он ее вычитывает и перелогинивается сам заново. Запилил так же алерты: в частности, сейчас при неудачной авторизации мы показываем пользователю, что что то пошло не так.

Сейчас пытаюсь сделать регистрацию: настроил Меш, что бы он позволял создавать пользователя без токена авторизации (проверил через curl - все работате), форма на UI уже есть. Проблема только в том, что не долетает запрос из ГУЯ до Меша. Что то опять с Корсом или еще подобной хренью...

**Comment by komadmi** [comment]
**Итого:**
1. Настройки в Меше для включения возможности создания пользователей без регистрации: Mesh Admin UI -> Premissions -> anonymous -> Users: set tick for 'Can create new users'
2. Создал форму для логина (почта/пароль)/регистрации (почта, пароль и имя).
3. При авторизации UI сохраняет auth token в cookies. При перезагрузке страницы кука извлекается и автоматически идет запрос на логин.

**Улучшения на будущее:**
1. После того, как определимся с моделью данных по пользователям, подкорректируем данные на UI, что бы вычитывать и отображать данные корректно. Сейчас, модель данных на тестовом образе Меша немного отличается от той, что есть на UI. Потому, есть ощущение, что данные не подгружаются. Это не так, достаточно глянуть логи приложения и нашего сервака.
2. Необходимо корректно обрабатывать коды ошибок Меш сервера и показывать сообщения с причиной ошибки. Например: пользователь не существует, не верный логин/пароль, пользователь уже есть в базе и т.д.
3. Подумать над интеграционными тестами.

**Comment by maxbl4** [comment]
Вот я хотел сказать, что пора тесты делать. У нас нет ресурсов на ручное тестирование, только автоматизация, только хардкор :)

**Comment by maxbl4** [comment]
Видимо придется делать скрипт, который в докере будет поднимать меш, а потом запускать тесты гуя. Надо изучить в первую очередь есть ли у меша урл для проверки хэлса. То есть мы стартуем контейнер и начинаем поллить хэлс меша. Когда получили ответ, запускаем наши тесты
